services:
  neo4j:
    image: neo4j:5.24.2
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - app-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - ART_URI=https://<ARTIFACTORYHOST>/api/repositories/configurations
      - ART_TOKEN=
    networks:
      - app-network

networks:
  app-network:
    driver: bridge