[tool.poetry]
name = "repo-graph"
version = "0.1.0"
description = ""
authors = ["Aleksei Pimanov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
neo4j = "^5.25.0"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
